name: nemo-ensemble
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.24.3
  - pandas=2.1.1
  - xarray=2024.2.0
  - dask=2024.2.1
  - matplotlib=3.8.0
  - jupyterlab=4.2.3
  - parcels=3.0.2
  - scipy=1.11.3
  - seaborn=0.12.2
  - pip=24.0
  - h3-py=3.7.7
prefix: /nethome/6525954/.conda/envs/nemo-ensemble
